version: '3'

services:
  web:
    build: ./docker/web
    container_name: web
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - "80:80"
    volumes:
      - ./app:/quest/app
    depends_on:
      - db

  db:
    build: ./docker/db
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306
    volumes:
      - "quest_data:/var/lib/mysql"
      - "./docker/db/init:/docker-entrypoint-initdb.d"
      - "./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf"
    restart: always

volumes:
  quest_data:
    driver: local
